# Generated by Django 3.1.1 on 2020-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiAmongUsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotice',
            name='current_notice',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
