# Generated by Django 3.1.1 on 2020-09-22 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AiAmongUsApp', '0002_usernotice_current_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotice',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernotice', to=settings.AUTH_USER_MODEL),
        ),
    ]
