# Generated by Django 3.1.1 on 2020-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiAmongUsApp', '0003_auto_20200922_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotice',
            name='current_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
